name: demo

on: [push]

jobs:
  demot:
    runs-on: ubuntu-latest
    name: Demo
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Run demo
        run:  pip install -r requirements.txt && python homework/eugene_okulik/Lesson_19/configured_db.py