name: Eokulik UI tests


on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: select test to run
        required: true
        type: choice
        default: smoke
        options:
          - smoke
          - regression
          - all

jobs:
  run-tests:
    name: Run autotests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependancies
        run: pip install -r requirements.txt
      - name: run smoke tests
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: cd ui_tests_eokulik && pytest -m smoke -v -s --alluredir=allure-results
      - name: run regression tests
        run: cd ui_tests_eokulik && pytest -m regression -v -s --alluredir=allure-results
        if: "github.event.inputs.deployment_target == 'regression'"
      - name: run all tests
        run: cd ui_tests_eokulik && pytest -v -s --alluredir=allure-results
        if: "github.event.inputs.deployment_target == 'all'"
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Install Allure
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.28.0/allure-2.28.0.tgz && 
          sudo tar -zxvf allure-2.28.0.tgz -C /opt/ &&
          sudo ln -s /opt/allure-2.28.0/bin/allure /usr/bin/allure
      - name: generate report
        run: allure generate -c ui_tests_eokulik/allure-results -o allure-report
      - name: Save report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention_days: 5
      
        
